apps/author/urls.py
from django.urls import path
from django.conf.urls import url

from .views import AuthorListView, AuthorDetailView

urlpatterns = [
    path('', AuthorListView.as_view(), name='author-list'),
    url(r'^detalle_autor/(?P<pk>\d+)$', AuthorDetailView.as_view(), name='author-detail'),
]

apps/messenger/urls.py
from django.urls import path, include

from .views import BotView

urlpatterns = [
    path('webhook',BotView.as_view(), name='fb-webhook'),
]

chatbot/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.conf import settings

from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^messenger/', include(('apps.messenger.urls','messenger'),namespace='messenger')),    
    path('', include(('apps.author.urls','author'),namespace='author')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/author/models.py
from django.db import models

class Author(models.Model):


    CHOICES_GENDER = [
        ('MASCULINO' , 'Masculino'),
        ('FEMENINO' , 'Femenino')
    ]

    first_name = models.CharField(
        max_length = 255,
        verbose_name = "Nombre autor",
        default = "Anonimo"
    )

    last_name = models.CharField(
        max_length = 255,
        verbose_name = "Apellido autor",
        default = "Anonimo apellido"
    )

    age = models.IntegerField(
        verbose_name = "Edad del Author",
        default = 0
    )

    gender = models.CharField(
        verbose_name = "genero del Autor",
        choices = CHOICES_GENDER,
        max_length = 255
    )

    biography = models.TextField(
        verbose_name = "Biografia del autor"
    )

    photo = models.ImageField(
        upload_to = "images/author",
        blank=True, 
        null=True
    )


    def __str__(self):
        return self.first_name

apps/blog/models.py
from django.db import models

# Create your models here.

apps/messenger/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _


class MessengerUser(models.Model):

	user_id = models.CharField(
		primary_key = True,
		max_length = 250
		
	)

	first_name = models.CharField(
		verbose_name=_('Nombre'),
		max_length = 250
	)

	last_name = models.CharField(
		verbose_name=_('Apellido'),
		max_length = 250
	)

	gender = models.CharField(
		verbose_name=_('Genero'),
		max_length = 250
	)

	timezone = models.CharField(
		verbose_name = _('Zona Horaria'),
		max_length = 255
	)


	image = models.CharField(
		verbose_name = _('image'),
		max_length = 255		
	)

	date = models.CharField(
		verbose_name = _('Fecha de Registro'),
		max_length = 255
	)


	class Meta:
		ordering = ['user_id']
		verbose_name_plural = "Usuarios"    

	def __str__(self):
		return self.first_name



class Dates(models.Model):

	name = models.CharField(max_length=255)
	date = models.DateTimeField()

	def __str__(self):
		return str(self.name)

apps/author/views.py
from django.shortcuts import render
from apps.author.models import Author
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

class AuthorListView(ListView):
    model = Author
    template_name = "autores.html"
    context_object_name = "autores"


class AuthorDetailView(DetailView):
    model = Author
    template_name = "detalle_autor.html"
    context_object_name = "autor"

apps/blog/views.py
from django.shortcuts import render

# Create your views here.

apps/messenger/views.py
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.http.response import HttpResponse
from django.views import generic

from .templates import recived_message

import requests
import json


class BotView(generic.View):

	def get(self, request, *args, **kwargs):
		if self.request.GET['hub.verify_token'] == 'token':
			return HttpResponse(self.request.GET['hub.challenge'])
		else:
			return HttpResponse('Error, invalid token')

	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
		return generic.View.dispatch(self, request, *args, **kwargs)


	def post(self, request, *args, **kwargs):

		incoming_message = json.loads(self.request.body.decode('utf-8'))
		for entry in incoming_message['entry']:
			for message in entry['messaging']:

				if 'message' in message:
					recived_message(message)


		return HttpResponse()

templates/autores.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

<!-- Blog Homepage-->
<section id="blog" class="blog-section section-padding">
    <div class="container">
        <div class="row text-center">
            <div class="col-xs-12">
                <h2 class="section-title wow zoomIn">Blog Post</h2>
            </div>
        </div>

        <div class="row content-row">
            {% for autor in autores %}
            <div class="col-sm-6 col-md-4">
                <article class="blog-post-wrapper">
                    <header class="entry-header">
                        <h2 class="entry-title"><a href="blog-single.html">{{ autor.first_name }} {{ autor.last_name }}</a></h2>
                    </header>

                    <div>
                        <img src="{{ autor.photo.url }}" width=200 height=200 class="img-responsive" alt="">

                        <div class="entry-footer clearfix">
                            <ul class="list-inline pull-left">
                                <li><span class="the-comments" > <a href="#"><i class="fa fa-comment"></i> 11</a></span></li>
                                <li><span class="the-like" > <a href="#"><i class="fa fa-heart"></i> 30</a></span></li>
                            </ul>

                            <a class="readmore pull-right" href="{% url 'author:author-detail' autor.id %}"><i class="fa fa-plus"></i></a>
                        </div>
                    </div>
                </article>
            </div>
            {% empty %}
                <h2 class="section-title wow zoomIn">Sin registros</h2>
            {% endfor %}
        </div>
    </div>
</section>
<!-- Blog end -->

{% endblock content %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">

	    <title>Autores-Posts</title>
	    <!-- Web Fonts -->
		<link href='http://fonts.googleapis.com/css?family=Roboto:400,900,700,500,300' rel='stylesheet' type='text/css'>
	    <!-- Flaticon CSS -->
	    <link href="{% static 'fonts/flaticon/flaticon.css' %}" rel="stylesheet">
	    <!-- font-awesome CSS -->
	    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	    <!-- Offcanvas CSS -->
	    <link href="{% static 'css/hippo-off-canvas.css' %}" rel="stylesheet">
	    <!-- animate CSS -->
	    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	    <!-- owl.carousel CSS -->
	    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
	    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
	    <!-- Bootstrap Core CSS -->
	    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	    <!-- Custom CSS -->
	    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	    <!-- Responsive CSS -->
	    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">

	    <script src="{% static 'js/vendor/modernizr-2.8.1.min.js' %}"></script>

        {% block extracss %}
        {% endblock extracss %}
	</head>


<body id="page-top" data-spy="scroll"  data-target=".navbar">

  <div id="st-container" class="st-container">
    <div class="st-pusher">
        <div class="st-content">
            <div class="st-content-inner">

			  	<header class="header">
                    {% include 'header.html' %}
				</header>

                <!-- slider content -->
                <div id="x-corp-carousel" class="carousel slide hero-slide" data-ride="carousel">
				    <!-- Indicators -->
				    <ol class="carousel-indicators">
				        <li data-target="#x-corp-carousel" data-slide-to="0" class="active"></li>
				        <li data-target="#x-corp-carousel" data-slide-to="1"></li>
				    </ol>

				    <!-- Wrapper for slides -->
				    <div class="carousel-inner" role="listbox">
				        <div class="item active">
				            <img src="{% static 'img/slider/slide-1.jpg' %}" alt="Hero Slide">
				            <!--Slide Image-->

				            <div class="container">
				                <div class="carousel-caption">
				                    <h1 class="animated lightSpeedIn">Creative Ideas &amp; Solutions</h1>

				                    <p class="lead animated lightSpeedIn">Energistically benchmark resource maximizing catalysts for change with <br> enterprise collaboration and idea-sharing. Dramatically evisculate.</p>

				                    <a class="btn btn-default animated lightSpeedIn" href="#">Get Started</a>
				                </div>
				                <!--.carousel-caption-->
				            </div>
				            <!--.container-->
				        </div>
				        <!--.item-->

				        <div class="item">
				            <img src="{% static 'img/slider/slide-2.jpg' %}" alt="Hero Slide">
				            <!--Slide Image-->

				            <div class="container">
				                <div class="carousel-caption">

				                    <h1 class="animated bounceIn">Clean &amp; Fresh Design</h1>

				                    <p class="lead animated bounceIn">Energistically benchmark resource maximizing catalysts for change with <br> enterprise collaboration and idea-sharing. Dramatically evisculate.</p>
				                    <a class="btn btn-default animated bounceIn" href="#">Work With Us Today</a>
				                </div>
				                <!--.carousel-caption-->
				            </div>
				            <!--.container-->
				        </div>
				        <!--.item-->
				    </div>
				    <!--.carousel-inner-->

				    <!-- Controls -->
				    <a class="left carousel-control" href="#x-corp-carousel" role="button" data-slide="prev">
				        <i class="fa fa-angle-left" aria-hidden="true"></i>
				        <span class="sr-only">Previous</span>
				    </a>
				    <a class="right carousel-control" href="#x-corp-carousel" role="button" data-slide="next">
				        <i class="fa fa-angle-right" aria-hidden="true"></i>
				        <span class="sr-only">Next</span>
				    </a>
				</div>
                 <!-- /end slider section -->

                {% block content %}
                    <!-- CONTENIDO DE LAS PAGINAS HIJAS -->
                {% endblock content %}

		        <!-- footer start -->
				<footer id="contact" class="footer-widget-wrapper">
                    {% include 'footer.html' %}
				</footer>
				<!-- footer end -->
        </div>
    </div>
    </div>


    	<!-- OFFCANVAS MENU -->
    	<div class="offcanvas-menu offcanvas-effect visible-xs">
	        <button type="button" class="close" aria-hidden="true" data-toggle="offcanvas" id="off-canvas-close-btn">&times;</button>
	        <h3>Sidebar Menu</h3>
	        <ul class="list-unstyled">
	            <li class="active"><a class="offcanvas-link" href="#page-top">Home<span class="sr-only">(current)</span></a></li>
	            <li><a class="offcanvas-link" href="#services">Services</a></li>
	            <li><a class="offcanvas-link" href="#work">Works</a></li>
	            <li><a class="offcanvas-link" href="#about">About</a></li>
	            <li><a class="offcanvas-link" href="#blog">Blog</a></li>
	            <li><a class="offcanvas-link" href="#contact">Contact</a></li>
	        </ul>
      	</div><!-- .offcanvas-menu -->
	</div><!-- /st-container -->


		<!-- Preloader -->
		<div id="preloader">
			<div id="status">
				<div class="status-mes"></div>
			</div>
		</div>


	    <!-- jQuery -->
	    <script src="{% static 'js/jquery.js' %}"></script>
	    <!-- Bootstrap Core JavaScript -->
	    <script src="{% static 'js/bootstrap.min.js' %}"></script>
	    <!-- wow.min.js -->
	    <script src="{% static 'js/wow.min.js' %}"></script>
	    <!-- smoothscroll -->
	    <script src="{% static 'js/smoothscroll.js' %}"></script>
	    <!-- twitterFetcher_min -->
	    <script src="{% static 'js/twitterFetcher_min.js' %}"></script>
	    <!-- owl.carousel -->
	    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
		<!-- Offcanvas Menu -->
		<script src="{% static 'js/hippo-offcanvas.js' %}"></script>
		<!-- inview -->
		<script src="{% static 'js/jquery.inview.min.js' %}"></script>
		<!-- stellar -->
		<script src="{% static 'js/jquery.stellar.js' %}"></script>
		<!-- countTo -->
		<script src="{% static 'js/jquery.countTo.js' %}"></script>
	    <!-- Scrolling Nav JavaScript -->
	    <script src="{% static 'js/jquery.easing.min.js' %}"></script>
		<!-- flickerPhoto -->
		<script src="{% static 'js/flickerPhoto.min.js' %}"></script>
		<!-- Shuffle.min js -->
		<script src="{% static 'js/jquery.shuffle.min.js' %}"></script>
	    <!-- GOGLE MAP -->
	    <script src="{% static 'https://maps.googleapis.com/maps/api/js' %}"></script>
	    <!-- Custom Script -->
		<script src="{% static 'js/scripts.js' %}"></script>
		
		{% block extrajs %}
			
		{% endblock extrajs %}
	</body>
</html>

templates/detalle_autor.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

<br><br><br>
<div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-md-9">

                <!-- Start article -->
                <article class="blog-post-wrapper">
                    <header class="post-thumbnail">
                        <div id="blogGalleryPost" class="carousel slide" data-ride="carousel">
                          <!-- Wrapper for slides -->
                          <img src="{{ autor.photo.url }}" width=100 height=100 class="img-responsive"  alt="">

                          <a class="left carousel-control" href="#blogGalleryPost" role="button" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                            <span class="sr-only">Previous</span>
                          </a>
                        </div>
                    </header>
                    <div class="entry-header">
                        <h2 class="entry-title"><a href="blog-single.html"> {{ autor.first_name }} {{ autor.last_name }} </a></h2>
                        <div class="entry-meta">
                            <ul class="list-inline">
                                <li><span class="the-author"><a href="#">Kraftt</a></span></li>
                                <li><span class="the-time"><a href="#">Feb 06, 2015</a></span></li>
                                <li><span class="the-category"><a href="#">Feature</a>,<a href="#">Lifestyle</a></span></li>
                             </ul>
                        </div><!-- /.entry-meta -->
                    </div><!-- /.entry-header -->
                    <div class="entry-content">
                        <p>{{ autor.biography }}</p>

                    </div><!-- /.entry-content -->

                    <footer class="entry-footer"> 
                        <div class="social-share">
                            <ul class="list-inline">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                            </ul>
                        </div>
                    </footer><!-- /.entry-footer -->
                </article>
                <!-- End article -->

                    <section class="comments-wrapper">
                        <h2>Comments</h2>
                        <hr>

                        <div class="row">
                            <div id="disqus_thread"></div>
                            <script>
                                (function () {
                                    var d = document, s = d.createElement('script');
                                    s.src = 'https://devzone-2.disqus.com/embed.js';
                                    s.setAttribute('data-timestamp', +new Date());
                                    (d.head || d.body).appendChild(s);
                                })();
                            </script>
                            <noscript>Please enable JavaScript to view the
                                <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
                            </noscript>
                        </div>

                    </section>

            </div><!-- /.col-md-9 -->

            <div class="col-xs-12 col-sm-4 col-md-3">
                <div class="sidebar-wrapper">
                      <aside class="widget widget_search">
                        <form role="search" method="get" class="search-form" action="getPost">
                            <label class="sr-only">Search for:</label>
                            <input type="search" class="form-control" placeholder="Search" value="" name="s" title="Search for:">
                            <button type="submit" class="search-submit" value=""><i class="fa fa-search"></i></button>
                        </form>
                    </aside>

                    <aside class="widget widget_popular">
                        <h2 class="widget-title">Popular post</h2>

                        <div class="media">
                          <div class="media-left">
                            <a href="#">
                              <img class="media-object" src="img/blog/popular-thumb.png" alt="">
                            </a>
                          </div><!-- /.media-left -->
                          <div class="media-body">
                            <h3 class="media-heading"><a href="#">Quisque nulla urna, convallis rutrum facer possim</a></h3>
                            <span class="the-time"><a href="#">Feb 11, 2015</a></span>
                          </div><!-- /.media-body -->
                        </div><!-- /.media -->

                        <div class="media">
                          <div class="media-left">
                            <a href="#">
                              <img class="media-object" src="img/blog/popular-thumb.png" alt="">
                            </a>
                          </div><!-- /.media-left -->
                          <div class="media-body">
                            <h3 class="media-heading"><a href="#">Quisque nulla urna, convallis rutrum facer possim</a></h3>
                            <span class="the-time"><a href="#">Jan 11, 2015</a></span>
                          </div><!-- /.media-body -->
                        </div><!-- /.media -->

                        <div class="media">
                          <div class="media-left">
                            <a href="#">
                              <img class="media-object" src="img/blog/popular-thumb.png" alt="">
                            </a>
                          </div><!-- /.media-left -->
                          <div class="media-body">
                            <h3 class="media-heading"><a href="#">Quisque nulla urna, convallis rutrum facer possim</a></h3>
                            <span class="the-time"><a href="#">Jan 8, 2015</a></span>
                          </div><!-- /.media-body -->
                        </div><!-- /.media -->

                        <div class="media">
                          <div class="media-left">
                            <a href="#">
                              <img class="media-object" src="img/blog/popular-thumb.png" alt="">
                            </a>
                          </div><!-- /.media-left -->
                          <div class="media-body">
                            <h3 class="media-heading"><a href="#">Quisque nulla urna, convallis rutrum facer possim</a></h3>
                            <span class="the-time"><a href="#">Jan 5, 2015</a></span>
                          </div><!-- /.media-body -->
                        </div><!-- /.media -->

                        <div class="media">
                          <div class="media-left">
                            <a href="#">
                              <img class="media-object" src="img/blog/popular-thumb.png" alt="">
                            </a>
                          </div><!-- /.media-left -->
                          <div class="media-body">
                            <h3 class="media-heading"><a href="#">Quisque nulla urna, convallis rutrum facer possim</a></h3>
                            <span class="the-time"><a href="#">Jan 2, 2015</a></span>
                          </div><!-- /.media-body -->
                        </div><!-- /.media -->

                    </aside>

                    <aside class="widget widget_categories">
                        <h2 class="widget-title">Blog Categories</h2>	
                        <ul>
                            <li><a href="#">Inspiration</a></li>
                            <li><a href="#">Life Style</a></li>
                            <li><a href="#">My Events</a></li>
                            <li><a href="#">Travel</a></li>
                            <li><a href="#">Technology</a></li>
                            <li><a href="#">Education</a></li>
                            <li><a href="#">Uncategorized</a></li>
                        </ul>
                    </aside>


                      <aside class="widget widget_archive">
                        <h2 class="widget-title">List Archived</h2>
                        <ul>
                            <li><a href="#">August 2014</a></li>
                            <li><a href="#">January 2014</a></li>
                            <li><a href="#">March 2012 </a></li>
                            <li><a href="#">January 2012</a></li>
                            <li><a href="#">March 2011</a></li>
                            <li><a href="#">October 2010 </a></li>
                        </ul>
                      </aside>

                    <aside class="widget widget_tag_cloud">
                        <h2 class="widget-title">Tag Cloud</h2>
                        <ul>
                            <li><a href="#">Post</a></li>
                            <li><a href="#">Graphic</a></li>
                            <li><a href="#">Internet</a></li>
                            <li><a href="#">Web Design</a></li>
                            <li><a href="#">Hosting</a></li>
                            <li><a href="#">Affaliate</a></li>
                        </ul>
                    </aside>

                    <aside class="widget widget_twitter_feed">
                        <h2 class="widget-title">Twitter Feed</h2>
                        <div id="twitterWidget">
                          <div class="twitter-widget owl-carousel"></div>
                        </div>
                    </aside>

                    <aside class="widget widget_flicker_photo">
                        <h2 class="widget-title">Flicker Photo</h2>
                        <ul id="photoStream"></ul>
                    </aside>


                    <aside class="widget widget_meta">
                        <h2 class="widget-title">Meta</h2>
                        <ul>
                            <li><a href="#">Login</a></li>
                            <li><a href="#">Entries RSS</a></li>
                            <li><a href="#">Comments RSS</a></li>
                            <li><a href="#">Wordpress.org</a></li>
                        </ul>
                    </aside>

                </div><!-- /.sidebar-wrapper -->
            </div><!-- /.col-md-3 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
{% endblock content %}

templates/footer.html
<div class="container">
    <div class="row">
        <div class="col-sm-3 col-md-3 col-md-offset-1">
            <div class="footer-widget footer-logo">
                <a href="#"><img src="img/footer-logo.png" alt=""></a>
            </div><!-- /.col-md-6 -->
        </div><!-- /.col-md-6 -->
        <div class="col-sm-3 col-md-2 col-lg-2">
            <div class="footer-widget">
                <h3>Social</h3>
                <ul>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Dribble</a></li>
                    <li><a href="#">Linkedin</a></li>
                </ul>
            </div><!-- /.footer-widget -->
        </div><!-- /.col-md-2 -->
        <div class="col-sm-3 col-md-3">
            <div class="footer-widget">
                <h3>Location</h3>
                <address>
                    50 Louis St. NW, Ste. 520<br>
                    Grand Rapids, MI 49503<br>
                    <!-- Google Map Modal Trigger -->
                    <a class="modal-map" data-toggle="modal" data-target="#cssMapModal" href="#">View on Google Maps</a>
                </address>


                <!-- Modal -->
                <div class="modal fade" id="cssMapModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Our Location</h4>
                        </div>
                        <div class="modal-body">

                        <div id="googleMap"></div>
                        
                        </div>
                    </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- End Modal -->

            </div><!-- /.footer-widget -->
        </div><!-- /.col-md-2 -->
        <div class="col-sm-3 col-md-3">
            <div class="footer-widget">
                <h3>Get in Touch</h3>
                <a href="#">+00 (123) 456 789</a>
                <a href="mailto:#">info@uicookies.com</a>
                <a class="feedback-modal" data-toggle="modal" data-target="#feedModal" href="#">Send us your feedback</a>

                <!-- Modal -->
                <div class="modal fade" id="feedModal" tabindex="-1" role="dialog" aria-labelledby="feedModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                    <div class="modal-content">
                        <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="feedModalLabel">Send us your feedback</h4>
                        </div>
                        <div class="modal-body">
                        <form id="contactForm" action="sendemail.php" method="POST">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">Name</label>
                                        <input id="name" name="name" type="text" class="form-control"  required="" placeholder="Name">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                    <label for="email">Email address</label>
                                    <input id="email" name="email" type="email" class="form-control" required="" placeholder="Email">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                    <label for="phone">Phone</label>
                                    <input id="phone" name="phone" type="text" class="form-control" placeholder="Phone">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                    <label for="subject">Subject</label>
                                    <input id="subject" name="subject" type="text" class="form-control" required="" placeholder="Subject">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group text-area">
                                <label for="message">Message</label>
                                <textarea id="message" name="message" class="form-control" rows="6" required="" placeholder="Message"></textarea>
                            </div>

                            <button type="submit" class="btn btn-primary">Send Message</button>
                        </form>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 text-center">
            <div class="copyright">
                <p>&copy; 2017 Orchid.  Design by : <a href="https://uicookies.com" title="uiCookies">uiCookies</a></p>
            </div>
        </div>
    </div>

</div>

templates/header.html
{% load staticfiles %}

<nav class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" >
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>

            <h1 class="logo"><a class="navbar-brand" href="index.html"><img src="{% static 'img/logo.png' %}" alt=""></a></h1>
        </div>

        <div class="collapse navbar-collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a class="page-scroll" href="#home">Home</a></li>
                <li><a class="page-scroll" href="#services">Services</a></li>
                <li><a class="page-scroll" href="#work">Works</a></li>
                <li><a class="page-scroll" href="#about">About</a></li>
                <li><a class="page-scroll" href="#blog">Blog</a></li>
                <li><a class="page-scroll" href="#contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>